# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  cmeapi:
    image: cmeapi
    build:
      context: .
      dockerfile: Backend/CME_api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:8000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
