version: '3.4'
services:
  Database:
    image: postgres:latest
    container_name: Database
    restart: always
    environment:
      POSTGRES_DB: cme_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cme12345
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c listen_addresses='*' -c password_encryption=md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5   

  Backend:
    image: ${DOCKER_REGISTRY-}backend
    container_name: Backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=Database;Port=5432;Database=cme_db;Username=postgres;Password=cme12345
      - ASPNETCORE_URLS=http://+:8000
    depends_on:
      Database:
        condition: service_healthy
    command: dotnet watch run --no-launch-profile --no-hot-restart
    volumes:
      - ./Backend/CME_api:/app
      - ~/.nuget/packages:/root/.nuget/packages
     
volumes:
  postgres_data: