// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CME_api.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250122223855_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("dataAtual")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataAtual");

                    b.Property<string>("email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int?>("groupid_group")
                        .HasColumnType("integer");

                    b.Property<string>("hashPassword")
                        .HasColumnType("text")
                        .HasColumnName("hashPassword");

                    b.Property<int>("id_user")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("name");

                    b.HasIndex("groupid_group");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("User_Group", b =>
                {
                    b.Property<int>("id_group")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_group");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_group"));

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.HasKey("id_group");

                    b.ToTable("User_Group");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("User_Group", "group")
                        .WithMany()
                        .HasForeignKey("groupid_group");

                    b.Navigation("group");
                });
#pragma warning restore 612, 618
        }
    }
}
